# Generated by Django 4.2 on 2023-04-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('rut', models.CharField(max_length=14)),
                ('descripcion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
