# Generated by Django 4.2 on 2023-04-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cliente_delete_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(default='Providencia', max_length=30),
            preserve_default=False,
        ),
    ]
