# Generated by Django 4.2 on 2023-04-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cliente_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('familia', models.CharField(max_length=14)),
                ('descripcion', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=20)),
                ('unidad_medida', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
