# Generated by Django 4.2 on 2023-05-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pFecha', models.DateTimeField()),
                ('pDocumento', models.CharField(max_length=10)),
                ('pControl', models.CharField(max_length=10)),
                ('pCliente', models.CharField(max_length=30)),
                ('pRIF', models.CharField(max_length=15)),
                ('pProducto', models.CharField(max_length=15)),
                ('pCantidad', models.IntegerField()),
                ('pPrecioU', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pBase', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pIVA', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pTotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pPagarUS', models.IntegerField()),
                ('pTotalUS', models.IntegerField()),
            ],
            options={
                'db_table': 'details',
            },
        ),
    ]
