# Generated by Django 4.2 on 2023-05-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sygbv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pCliente',
            field=models.CharField(max_length=50),
        ),
    ]
